import type { Event } from "@/lib/types"

export const DUMMY_EVENTS: Event[] = [
  {
    id: "1",
    league: "English Premier League",
    homeTeam: "Arsenal",
    awayTeam: "Manchester United",
    time: "15:00",
    status: "Upcoming",
    venue: "Emirates Stadium",
    channels: ["Sky Sports", "BT Sport"],
  },
  {
    id: "2",
    league: "NBA",
    homeTeam: "Los Angeles Lakers",
    awayTeam: "Golden State Warriors",
    time: "19:30",
    status: "Upcoming",
    venue: "Crypto.com Arena",
    channels: ["ESPN", "TNT"],
  },
  {
    id: "3",
    league: "ATP Finals",
    homeTeam: "Novak Djokovic",
    awayTeam: "Rafael Nadal",
    time: "14:00",
    status: "Upcoming",
    venue: "O2 Arena",
    channels: ["Tennis Channel", "ESPN"],
  },
  {
    id: "4",
    league: "MLB",
    homeTeam: "New York Yankees",
    awayTeam: "Boston Red Sox",
    time: "19:05",
    status: "Upcoming",
    venue: "Yankee Stadium",
    channels: ["ESPN", "MLB Network"],
  },
  {
    id: "5",
    league: "Ligue 1",
    homeTeam: "Paris Saint-Germain",
    awayTeam: "Olympique Marseille",
    time: "20:45",
    status: "Upcoming",
    venue: "Parc des Princes",
    channels: ["beIN SPORTS"],
  },
  {
    id: "6",
    league: "Formula 1 - Bahrain Grand Prix",
    homeTeam: "Max Verstappen",
    awayTeam: "Lewis Hamilton",
    time: "14:00",
    status: "Upcoming",
    venue: "Bahrain International Circuit",
    channels: ["ESPN", "Sky Sports F1"],
  },
  {
    id: "7",
    league: "WTA Finals",
    homeTeam: "Serena Williams",
    awayTeam: "Naomi Osaka",
    time: "19:00",
    status: "Upcoming",
    venue: "Fort Worth Convention Center",
    channels: ["ESPN", "Tennis Channel"],
  },
]
